### ISSUE TITLE
Fail to Build on ancient Windows 8.1 machine/Visual Studio 12.0

### ISSUE THREAD

**Issue by AntC2** [augustss/MicroHs#466]
Distro v0.16.0 "Try to placate VS12" -- in response to to-and-fro Discourse thread

Thank you for trying to be ancient Windows-friendly. (And I hope I'm not presuming by creating an Issue/by all means close if not the right process. None of the below looks likely to be easily fixed.)

v 0.16 does load to Vis Studio 12.0, and Build starts to do something, but doesn't get very far:

* I loaded by File > New > Project from existing code ...;
* said it was C++ -- this is the default, but might be significant, see syntax errors below ;
* pointed it at the MicroHs-master directory;
* took defaults for all the other questions.

```
1>------ Build started: Project: MicroHS, Configuration: Debug Win32 ------
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(942,5): warning MSB8027: Two or more files with the name of extra.c will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are src\runtime\c64\extra.c, src\runtime\esp32\extra.c, src\runtime\micro\extra.c, src\runtime\mingw\extra.c, src\runtime\stm32f4\extra.c, src\runtime\unix\extra.c, src\runtime\windows\extra.c.
1>  machdep.c
1>  hsimp.c
1>tests\hsimp.c(2): fatal error C1083: Cannot open include file: 'Callback_stub.h': No such file or directory
1>  hsasp.c
1>tests\hsasp.c(3): fatal error C1083: Cannot open include file: 'mhsffi.h': No such file or directory
1>  ForExp.c
1>tests\ForExp.c(2): fatal error C1083: Cannot open include file: 'ForExp_stub.h': No such file or directory
1>  extra.c
1>src\runtime\windows\extra.c(17): warning C4163: '_BitScanForward64' : not available as an intrinsic function
1>src\runtime\windows\extra.c(18): warning C4163: '_BitScanReverse64' : not available as an intrinsic function
1>src\runtime\windows\extra.c(20): error C2054: expected '(' to follow 'inline'
1>src\runtime\windows\extra.c(20): error C2146: syntax error : missing ')' before identifier 'arg'
1>src\runtime\windows\extra.c(20): error C2085: 'ffs' : not in formal parameter list
1>src\runtime\windows\extra.c(20): error C2146: syntax error : missing ',' before identifier 'arg'
1>src\runtime\windows\extra.c(20): error C2059: syntax error : ')'
1>src\runtime\windows\extra.c(21): error C2143: syntax error : missing ';' before '{'
1>src\runtime\windows\extra.c(36): error C2061: syntax error : identifier 'uint64_t'
1>src\runtime\windows\extra.c(36): error C2059: syntax error : ';'
1>src\runtime\windows\extra.c(36): error C2146: syntax error : missing ')' before identifier 'x'
1>src\runtime\windows\extra.c(36): error C2061: syntax error : identifier 'x'
1>src\runtime\windows\extra.c(36): error C2059: syntax error : ')'
1>src\runtime\windows\extra.c(36): error C2449: found '{' at file scope (missing function header?)
1>src\runtime\windows\extra.c(43): error C2059: syntax error : '}'
1>src\runtime\windows\extra.c(43): error C2014: preprocessor command must start as first nonwhite space
...  /* and plenty more syntax errors in extra.c   */
``` 

Of those three allegedly missing include files, the two `_stub.h` are indeed not on the machine. The `mshffi.h` is in the downloads `\src\runtime\`. `hsasp.c` also includes and seems to find ok `hsasp.h` -- which is in `\tests\`. (Is it essential to compile the stuff in `\tests\`? Should I point Vis Studio only at the `\src\` subdir?)

Re the `error C2054: expected '(' to follow 'inline'`, AI Overview thinks this is because of C++ code appearing in a `.c` extension file. " While Modern C++ supports inline, older MSVC compilers (pre-C11) only recognize it in C++ mode." Some of those syntax errors I can clear by Project > Properties > Configuration > C/C++ > Advanced > Compile as > C++ Code (/TP).

But still a whole bunch of syntax errors, starting `extra.c` (20): `error C2065: 'int64_t' : undeclared identifier`. (Looks like that's declared in HsFFI.h; but I can't see where/how it's supposed to be included.)

As I understand it, Vis Studio ignores `Makefile`s. But just in case, I blew everything away and reloaded, renamed `Makefile`; cloned `Makefile.windows` as bare `Makefile`. This gave the same fails to build.

I also tried `nmake` again. And again it failed at lack of `inttypes.h`.

**Comment by augustss** [comment]
I've made an AppVeyor account.  I'll make sure it works on Visual Studio 2013, 2015, 2017, 2019, 2022, and 2026.
On 32 and 64 bit.

The code is not make to be all slurped in Visual Studio, it's designed to be compild with `make`/`nmake`.
That's why you see some of those errors.

I hope your computer is not from 2013.  MicroHs is not fast.

**Comment by AntC2** [comment]
For the record: I did manage to build gmhs, using a MinGW/msys/.../bash I had lying around.

Note for your docos: it seems to need a recent version of GHC -- I got 9.10 to work, but not the older version of GHC I first tried.

But now how can I get gmhs to do anything useful? It'll produce a `.comb` or a `.c`, but gives unix errors trying to produce a `.exe`.

I can't use gmhs in `--interactive` nor `-r` run immediate. `module Main` function `main :: IO()` doesn't seem to get anywhere.

(You do seem to have fixed one of the long-standing FunDep issues in GHC, not another one in my 'top ten' -- but hard to be sure if I can't run anything or ask for a `:type`.)

**Comment by augustss** [comment]
Give it another try to build with nmake. It should work now. I'm working on getting installing to work properly, so I'm not declaring victory yet.

**Comment by augustss** [comment]
I believe it builds now.  And (for the first time ever) `nmake -f Mafile.windows install` should work.

**Comment by AntC2** [comment]
I took a fresh download from github. For the record

```
main.c
eval.c
src/runtime/windows\config.h(105) : fatal error C1083: Cannot open include file:
 'stdbool.h': No such file or directory
mhs.c
src/runtime/windows\config.h(105) : fatal error C1083: Cannot open include file:
 'stdbool.h': No such file or directory
```

* `stdbool.h` is on the machine, in `C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\`, so I added that to the `path` and checked it with a `where`. (Turns out `inttypes.h` is in the same directory.) Note `cl` and `nmake` are in `\VC\bin\`, so I have both directories in my path.) That didn't clear the error.
* I copied `stdbool.h` to `\MicroHs-master\src\runtime\windows\` (and `inttypes.h`). That cleared that error, but just reported `stdint.h` not found.
* I don't understand why `cl` isn't scanning the `path` for `#include`s.
* I carried on copying further `.h` files from `\VC\include\` (nearly a dozen of). Eventually ...
* `Windows.h` not found. That's on my machine, but in `\Microsoft SDKs\`. (Presumably when I installed Vis Studio, that didn't think I needed it and/or I didn't expect I was going to be compiling C++.) Again copied into `\src\runtime\windows`.
* Now it wants `winapifamily.h` -- which is in `Windows Kits`. And then `sdkddkver.h` ...

I'm stopping. This is more jiggery-pokery/more command window dodginess than is reasonable. I never wanted to be a C++ developer.

I won't be using MicroHS. It's understandable to not support ancient machines. (As a reminder, that's what I expected all along.)

**Comment by augustss** [comment]
I'm not sure why it's not working for you.
I now run CI tests on all Visual Studio versions from 2013-2022.  They all
build without problem. Perhaps you have a non-standard setup.

But there's no great point in continuing this, since you don't really need
MicroHs.

**Comment by augustss** [comment]
<img width="1028" height="870" alt="Image" src="https://github.com/user-attachments/assets/40da825f-4d96-4396-9032-c820db85c673" />
